### ISSUE TITLE
문의 작성 및 구매페이지

### ISSUE THREAD

**Issue by Banal972** [solo-service/shopingmall#11]
### Todo

- [x] 문의페이지 UI
- [x] 텍스트 에디터
- [x] 구매페이지 UI
- [x] 구매완료 UI
- [x] 구매완료시 DB저장
- [x] 주문내역 UI
- [x] 주문 내역 기능
- [x] 주문내역 상세페이지 UI
- [x] 주문 상세내역 기능

### 작업 기간

2024.05.17 ~ 2024.05.19
