### ISSUE TITLE
리스트, 상세 페이지 UI 및 기능

### ISSUE THREAD

**Issue by Banal972** [solo-service/shopingmall#4]
### Todo

- [x] 카테고리별로 리스트페이지 UI
- [x] 리스트별 상세 페이지 UI 
- [x] 카데고리별 데이터 불러오기
- [x] 리스트별 데이터 불러오기

### 작업 기간

2024.05.10 ~ 2024.05.17
